version: "3"
services:
  order_service:
    build: ./order_service
    ports:
      - "3000:3000"
      - "50052:50051"
  user_service:
    build: ./user-service
    ports:
      - "3001:5055"
      - "50051:50051"
