# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any necessary packages
RUN apt-get update && apt-get install -y \
    gcc \
    protobuf-compiler \
    python3-dev \
 && rm -rf /var/lib/apt/lists/*

# Copy the protos directory into the container
COPY protos /app/protos

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m grpc_tools.protoc -I. --python_out=. --pyi_out=. --grpc_python_out=. protos/user.proto

# Make port 50051 available to the world outside this container
EXPOSE 50051

# Run the command to start the gRPC server
CMD ["python", "main.py"]
