# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\tmypackage\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"2\n\x11\x43reateUserRequest\x12\x1d\n\x04user\x18\x01 \x01(\x0b\x32\x0f.mypackage.User\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x8d\x01\n\x0bUserService\x12=\n\nCreateUser\x12\x1c.mypackage.CreateUserRequest\x1a\x0f.mypackage.User\"\x00\x12?\n\x0bGetUserById\x12\x1d.mypackage.GetUserByIdRequest\x1a\x0f.mypackage.User\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=25
  _USER._serialized_end=57
  _CREATEUSERREQUEST._serialized_start=59
  _CREATEUSERREQUEST._serialized_end=109
  _GETUSERBYIDREQUEST._serialized_start=111
  _GETUSERBYIDREQUEST._serialized_end=143
  _USERSERVICE._serialized_start=146
  _USERSERVICE._serialized_end=287
# @@protoc_insertion_point(module_scope)
